### ISSUE TITLE
Add credits

### ISSUE THREAD

**Issue by samreid** [phetsims/sound-waves#12]
From a TODO, we need to add credits in sound-main.ts

**Comment by matthew-blackman** [comment]
Credits are in. @samreid can you review if this is sufficient for acknowledging previous work and external partners?

**Comment by Nancy-Salpepi** [comment]
Thanks for updating the QA credits @matthew-blackman. 
Was Marla supposed to be added? I don't know the scope of her involvement. 

Also, from https://github.com/phetsims/sound-waves/issues/12#issuecomment-1684368767, @samreid do the credits look good to you?

**Comment by samreid** [comment]
Comparing to other credits dialogs, this one appears to be a sentence fragment.  This sim has:

> thanks: 'Jan Willems, University of Leuven, for supporting the conversion of this simulation from Java to HTML5.'

But other sims have wording like:

> thanks: 'Thanks to Actual Concepts for working with the PhET development team to convert this simulation to HTML5.'

or

> thanks: 'We gratefully acknowledge the support of ECO Canada for helping to fund this sim.'

or 

>       thanks: 'We gratefully acknowledge support from STROBE NSF Science & Technology Center Grant DMR-1548924.   Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation.

etc.

Number play also just has a name list though.

**Comment by matthew-blackman** [comment]
Credits are up to date on both the sim and sim page. Closing.
