### ISSUE TITLE
Review sim strings for dynamic length and localization

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/sound-waves#23]
The sim is in a good place as far as features. We'd like to take a look at dynamic strings and localization before moving into dev testing.

**Comment by samreid** [comment]
Please be aware of constraints in the stopwatch node described in https://github.com/phetsims/scenery-phet/issues/814

**Comment by marlitas** [comment]
The patternString implementation has been committed above. Over to you for review @matthew-blackman!

**Comment by matthew-blackman** [comment]
Pattern string for frequency slider is looking great. Nice work @marlitas! The sim strings are looking good for the scope of this "quick and dirty" release. It should be noted that when revisitng this sim, we want to spend some time working on dynamic strings for the RulerNode and StopwatchNode. Closing.
