### ISSUE TITLE
Audio control 'Speaker' option doesn't have a sonified location

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/sound-waves#25]
The current design of the sim has a checkbox for 'Audio Enabled', along with two radio buttons for 'Speaker' and 'Listener'. When reviewing the sim features, it was discovered that this design created problems with pedagogy and UX.

UX issues:
- Setting the default value to 'Speaker' makes it unclear what location is being sonified. When this option is checked, moving the person closer or further from the speaker does not have an effect on the audio. During testing, @KatieWoe and I found to be confusing and initially thought it was a bug. At the very least, I recommend making the default setting 'Listener' so that the audio represents the sound heard by the person.

Pedagogical issues:
- Sonification should make clear what location is being represented by the audio. Sound intensity approaches infinity as distance approaches zero, so the sim is already choosing a "default" distance for the 'Speaker' setting but it is not clear to the user what this distance is.
- The speaker does not have an "absolute" sound intensity that can be sonified. Sound intensity is inherently connected to distance from the source, and with the 'Speaker' option selected it is unclear where the sonified location is for this setting.
- In the 'Air Pressure' screen, the speaker will not create any sound waves if all air is removed from the speaker box. On this screen, the 'Speaker' setting still plays sound. This is especially confusing, because there would be no sound waves produced anywhere.

I recommend removing the 'Speaker' setting altogether and set the audio checkbox to 'Enable Listener Audio. This would only enable sonificiation on the screens in which there is a listener, which I feel is more than enough for users to explore sonification and the roles of frequency, amplitude and interference throughout the sim. This allows the user to still hear what the different frequencies and amplitudes of the speaker will sound like to the person on the screen in a more straightforward and pedagogically rigorous way.

**Comment by matthew-blackman** [comment]
@KatieWoe I set the audio to always play what the Listener will hear, and only show this option on screens which have a person. Can you double-check that the audio is working correctly?

**Comment by KatieWoe** [comment]
This change has been made. I'm not sure the "speaker" option should be removed entirely. Especially on the last screen where the listener can't go inside the box.
