### ISSUE TITLE
Possible to lose ruler

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/sound-waves#27]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/972, on the Measure Screen it is possible to lose the ruler on the bottom of the screen.

**Steps to reproduce**
1. On the Measure Screen, drag the ruler off screen and let go.

**Visuals**

https://github.com/phetsims/sound-waves/assets/87318828/7c9a4d42-815b-4554-b6c8-3c87059a49f6

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-dev.5/phet/sound-waves_all_phet.html
Version: 1.0.0-dev.5 2023-08-21 17:16:24 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1196x618
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by matthew-blackman** [comment]
Good catch! This should be fixed now. Back to you for testing @Nancy-Salpepi! 😄

**Comment by Nancy-Salpepi** [comment]
Looks fixed on my end 🙂. Closing!

**Comment by matthew-blackman** [comment]
Reopening to confirm that this is fixed during next dev test.

**Comment by KatieWoe** [comment]
Looks good in rc.1
