### ISSUE TITLE
Unable to load debug version of sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sound-waves#28]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/972
Trying to load the debug version of the sim fails and the errors pictured below show up in the console.

**Visuals**
![bugdebug](https://github.com/phetsims/sound-waves/assets/41024075/b735e7a0-689c-4ac9-9806-6e3d7e7d2f9d)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-dev.5/phet/sound-waves_all_phet.html
Version: 1.0.0-dev.5 2023-08-21 17:16:24 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by matthew-blackman** [comment]
This looks like it has been fixed by the commits to #26. Back to you for confirmation @KatieWoe

**Comment by KatieWoe** [comment]
I think this is ok on main, but it's a bit hard to tell without a built debug version.

**Comment by KatieWoe** [comment]
This seems solved in rc.1
