### ISSUE TITLE
What should happen when I change amplitude with frequency=0Hz?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/sound-waves#30]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/972, the behavior is different between 1.0.0-dev.5 and the java sim when I change the amplitude while the frequency has a value of 0 Hz. In the java sim nothing happens while in the current dev version a wave is produced. I wasn't sure what the behavior should be. 

**Steps to reproduce**
Compare these steps in both versions:
1. On any screen, move the frequency slider to 0 Hz. 
2. Once there are no more waves on the screen, move the amplitude slider.

**Visuals**

https://github.com/phetsims/sound-waves/assets/87318828/ddccd585-4ade-4f28-b8fc-85889acc561c

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-dev.5/phet/sound-waves_all_phet.html?
Version: 1.0.0-dev.5 2023-08-21 17:16:24 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1099x624
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Hey @matthew-blackman I'm not sure what to do here.

**Comment by matthew-blackman** [comment]
The frequency slider is behaving well with the new range of 100 - 1000 Hz. This issue can be closed 😄
