### ISSUE TITLE
Panels become misaligned with stringTest=double

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/sound-waves#32]
**Test device**
Dell

**Operating System**
Win10

**Browser**
Chrome 

**Problem description**
For https://github.com/phetsims/qa/issues/972, with ?stringTest=double, the panels on the Air Pressure screen become misaligned. 

**Visuals**
<img width="407" alt="Screenshot 2023-08-22 at 8 33 17 AM" src="https://github.com/phetsims/sound-waves/assets/87318828/6a6c8f0a-5597-4fcf-bfd0-f1fb59f704d0">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬:‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-dev.5/phet/sound-waves_all_phet.html?stringTest=double
Version: 1.0.0-dev.5 2023-08-21 17:16:24 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language: en-US
Window: 1433x729
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by matthew-blackman** [comment]
The panel horizontal alignment has been fixed and is updating nicely for me. Looking at the vertical spacing, things are looking good enough to me until the strings get *really* long. The cost to implement a dynamic approach for vertical spacing is nontrivial and may be outside the scope of this release.

@samreid / @marlitas would like to hear your thoughts on this.

**Comment by KatieWoe** [comment]
The text boxes now stay in line. However, the text looks quite small when doubled. The Audio Controls box looks particularly odd.
![inline](https://github.com/phetsims/sound-waves/assets/41024075/968e44be-5661-4eb3-8636-86670c56084f)

**Comment by marlitas** [comment]
Perhaps we can increase the max width on some of the text in these panels. But I agree. Full dynamic layout is not expected to be supported in this release.

**Comment by matthew-blackman** [comment]
This has been addressed in the commits on https://github.com/phetsims/sound-waves/issues/37. Please confirm.

**Comment by KatieWoe** [comment]
I'm still seeing the oddly sized text with long strings on the last screen. With dynamic strings and without.
<img width="203" alt="stillsmall" src="https://github.com/phetsims/sound-waves/assets/41024075/4fbc4b7e-ff88-44db-9c56-25b7e9d86ce6">

**Comment by Nancy-Salpepi** [comment]
this looks good to me on main:
<img width="287" alt="Screenshot 2023-09-06 at 5 28 11 PM" src="https://github.com/phetsims/sound-waves/assets/87318828/2ecdf332-2e95-49cc-a702-d18232b01c13">

**Comment by matthew-blackman** [comment]
This issue has been fixed, confirmed in RC1. Closing.
