### ISSUE TITLE
Reseting while trying to pulse at 0 hz disables pulsing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sound-waves#33]
**Test device**
Samsung Chromebook
**Operating System**
ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/972. Related to https://github.com/phetsims/sound-waves/issues/30. If you set the frequency on the Reflection screen to 0 hz, then try to pulse, the pulse button is stuck. If you then reset all in this state, the pulse feature is permanently unusable until the sim is reloaded. If you change frequency before resetting the permanent unusability may not happen.
**Steps to reproduce**
1. Go to the reflection screen
2. Set scene to pulse
3. Change the frequency to 0
4. Hit the pulse button
5. Hit reset all

**Visuals**

https://github.com/phetsims/sound-waves/assets/41024075/4eed6fce-5623-4703-838f-6263fdc988e4

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-dev.5/phet/sound-waves_all_phet.html
Version: 1.0.0-dev.5 2023-08-21 17:16:24 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by matthew-blackman** [comment]
This is fixed on main. Ready for spot check.

**Comment by KatieWoe** [comment]
Looks fixed in main

**Comment by Nancy-Salpepi** [comment]
This looks good to me in rc.2. Closing.
