### ISSUE TITLE
Extreme low frequencies are problematic

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/sound-waves#34]
In dev testing, it was noted that extreme low frequencies (under 50 Hz) lead to issues such as https://github.com/phetsims/sound-waves/issues/30 and https://github.com/phetsims/sound-waves/issues/33, as well as visual problems with the frame-by-frame animation of the vibrating speaker.

These extreme low frequencies do not add to the pedagogical value of the sim, and I recommend capping the minimum frequency at 100 Hz. This will still allow users to study the relationship between frequency and wavelength, without breaking the limitations of the speaker animation system and Amplitude / Pulse controls.

**Comment by matthew-blackman** [comment]
The speaker frequency range has been update to 100Hz - 1000Hz and is working nicely. Closing this issue and will track remaining work in https://github.com/phetsims/sound-waves/issues/30 and https://github.com/phetsims/sound-waves/issues/33.

**Comment by matthew-blackman** [comment]
Reopening this issue for spot-check during RC 1.0

**Comment by KatieWoe** [comment]
This change has been implemented and looks alright in rc.1
