### ISSUE TITLE
Waves look odd when the wall is moved while paused

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/sound-waves#36]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.5

**Browser**
safari 16.5

**Problem description**
For https://github.com/phetsims/qa/issues/974, this might be outside the scope of this release, but it looks really odd to me that the wave doesn't disappear/update when the wall is moved during pause. 

**Steps to reproduce**
1. Go to the Reflection Screen and pause the sim after waves have reached the wall
2. Move the Wall Angle slider all the way to the right 
3. Press play and then pause again
4. Move the Wall Position slider all the way to the right

**Visuals**
<img width="599" alt="Screenshot 2023-08-30 at 1 37 19 PM" src="https://github.com/phetsims/sound-waves/assets/87318828/63c448cd-ff3b-410d-962a-0324cda5abf1">

<img width="599" alt="Screenshot 2023-08-30 at 1 37 32 PM" src="https://github.com/phetsims/sound-waves/assets/87318828/2226cc75-bfa9-4b83-999a-54b9e70a0188">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-rc.2/phet/sound-waves_all_phet.html
Version: 1.0.0-rc.2 2023-08-28 14:05:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1346x717
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
What is really interesting is....if I take a screenshot from the PhET menu, it shows the "updated" wave.
Here is what the screen looks like:
<img width="579" alt="Screenshot 2023-09-01 at 9 51 08 AM" src="https://github.com/phetsims/sound-waves/assets/87318828/699f7ad5-3412-4a75-a7d3-a08bf848f4ff">
And here is the screenshot taken from the PhET menu:
<img width="579" alt="Screenshot 2023-09-01 at 9 51 25 AM" src="https://github.com/phetsims/sound-waves/assets/87318828/d9d5c213-519d-4dbc-98a5-d0a22be0fe27">

**Comment by Nancy-Salpepi** [comment]
I see something similar with the screenshots when moving the speaker while paused on the Two Sources Screen.
Steps:
1. On the Two Sources screen wait a couple of seconds and then press pause
2. Move the speaker to the top of the play area
3. Take a screenshot

What it looks like in the sim:
<img width="638" alt="Screenshot 2023-09-01 at 1 12 04 PM" src="https://github.com/phetsims/sound-waves/assets/87318828/1aea4f6e-cb6a-4adc-bb02-e44fc575e8ba">

What the screenshot looks like:
![Sound Waves screenshot (8)](https://github.com/phetsims/sound-waves/assets/87318828/6226fc06-5f4c-4d89-9c9e-6c670206ecff)

**Comment by KatieWoe** [comment]
Looks ok to me on main.

**Comment by Nancy-Salpepi** [comment]
This looks great now!

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2! Closing.
