### ISSUE TITLE
Minor pointer area overlap

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sound-waves#38]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/974
There is a minor pointer overlap between the air density slider and the air density reset button on the last screen.

**Visuals**
![minoroverlap](https://github.com/phetsims/sound-waves/assets/41024075/4919463c-b9d7-46e9-ab94-e8d7739b9e7a)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-rc.2/phet/sound-waves_all_phet.html?showPointerAreas
Version: 1.0.0-rc.2 2023-08-28 14:05:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by matthew-blackman** [comment]
This is ready for QA spot-check on main

**Comment by Nancy-Salpepi** [comment]
Looks good to me in rc.2. Closing.
