### ISSUE TITLE
Preferences should have localization

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/sound-waves#39]
The sim will support translation, so we should have a localization menu in the preferences.

**Comment by matthew-blackman** [comment]
@marlitas and I checked in on this and it looks like the sim has a localization tab when the query parameter &locales=* is added. This looks correct to us.

QA can you confirm that the localization tab appears when it should?

**Comment by Nancy-Salpepi** [comment]
@matthew-blackman and @marlitas the localization tab appears when the query parameter is added to the sim on main. 
It doesn't appear when added to the rc.2 version. I think that is correct behavior, but thought I would double check with you before closing.

**Comment by matthew-blackman** [comment]
@marlitas and I confirmed this - thanks @Nancy-Salpepi! We should be good to close.
