### ISSUE TITLE
Repo name does not match legacy project name

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sound-waves#44]
Similar to https://github.com/phetsims/faradays-electromagnetic-lab/issues/91. 

The Java version was called "Sound" with a project name of `sound`. The HTML5 version was renamed "Sound Waves" and its repo name is `sound-waves`. Both versions are currently visible on the website, which shouldn't happen for ports.
<img width="895" alt="Screenshot 2024-04-01 at 9 11 40 AM" src="https://github.com/phetsims/sound-waves/assets/8419308/6934372a-19ae-407d-922d-0f2002874659">

@mattpen can you please add a mapping of `sound` to `sound-waves` to the website?

**Comment by mattpen** [comment]
I'm going to try this first on ox-dev, as this would be the first java-port community contribution sim, and I'm not sure how the sim pages will behave.

**Comment by mattpen** [comment]
It looks like this is being published as a Community Sim (and does not have the java Run Options page).  @arouinfar - is this intended, or would you rather show the page that can run the java or the community sim?

**Comment by arouinfar** [comment]
Good question @mattpen. I wouldn't show the Java run options on Community sims. The cheerpj/java options are nice for Prototypes, which are often incomplete. However, I don't think we would publish  an incomplete sim as a Community contribution.

**Comment by mattpen** [comment]
Sounds great, this is staged for the Maintenance Y release (will be deployed by 4/25)

**Comment by mattpen** [comment]
This was deployed some time ago. Closing.
